{
 "title": "nyc_green_taxi_metrics",
 "time": { "from": "2023-02-23T05:00:47.467Z", "to": "2023-04-04T14:58:42.899Z" },
 "panels": [
  {
   "title": "column_quantile_metric",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", column_quantile_metric FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "dataset_summary_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", dataset_summary_values FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "prediction_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "dataset_corr_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", dataset_corr_values FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "num_drifted_columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "share_missing_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM nyc_green_taxi_metrics LIMIT 50 "
    }
   ]
  }
 ]
}